server:
  port: 80
spring:
  application:
    name: cloud-consul-consumer-order
  cloud:
    consul:
      host: 192.168.54.125
      port: 8500
      discovery:
        service-name: ${spring.application.name}