server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:liufengtao2018/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/